plugins {
    id 'java-library'
}

group 'org.mentalizr'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
}

dependencies {
    api libs.mongodb.driver.sync

    implementation libs.m7r.commons
    implementation libs.m7r.backendConfig
    implementation libs.m7r.serviceObjects

    implementation libs.ap.utils.core

    implementation libs.jakarta.xml.bind.api
    implementation libs.qos.logback
    implementation libs.slf4j.julToSlf4j // Leitet java.util.logging um auf slf4j, für mongo-java-driver

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}
